package sistema;

import dao.PedidoDAO;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.Pedido;

/**
 *
 * @author Eduardo
 */
public class VerPedidos extends javax.swing.JFrame {
    private JTable tabelaPedidos;
    private PedidoDAO pedidoDAO;
    private List<Pedido> pedidosAtuais = new ArrayList<>();
    private JButton btnAtualizar;
    
    /**
     * Creates new form VerPedidos
     */
    public VerPedidos() {
        initComponents();
        setTitle("Pedidos em Andamento");
        setSize(700, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        pedidoDAO = new PedidoDAO();
        tabelaPedidos = new JTable();
        JScrollPane scrollPane = new JScrollPane(tabelaPedidos);

        btnAtualizar = new JButton("Atualizar");
        btnAtualizar.addActionListener(e -> carregarPedidos());

        JPanel painelBotoes = new JPanel();
        painelBotoes.add(btnAtualizar);

        add(scrollPane, BorderLayout.CENTER);
        add(painelBotoes, BorderLayout.SOUTH);

        carregarPedidos();

        // Atualiza automaticamente a cada 10 segundos
        Timer timer = new Timer(10000, e -> carregarPedidos());
        timer.start();

        setVisible(true);
    }

    private void carregarPedidos() {
        List<Pedido> novosPedidos = pedidoDAO.listarTodosPedidosEmAndamento();

        // Se os pedidos forem iguais aos anteriores, não faz nada
        if (iguais(pedidosAtuais, novosPedidos)) {
            return;
        }

        // Atualiza a tabela e a lista atual
        pedidosAtuais = novosPedidos;

        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "UUID Cliente", "Valor Total", "Status"}, 0);

        for (Pedido p : novosPedidos) {
            model.addRow(new Object[]{p.getId(), p.getUuidCliente(), p.getValorTotal(), p.getStatus()});
        }

        tabelaPedidos.setModel(model);
    }
    
    private boolean iguais(List<Pedido> a, List<Pedido> b) {
        if (a.size() != b.size()) return false;

        for (int i = 0; i < a.size(); i++) {
            Pedido p1 = a.get(i);
            Pedido p2 = b.get(i);

            if (p1.getId() != p2.getId()) return false;
            if (!p1.getStatus().equals(p2.getStatus())) return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
